In [6]:
print("abc")

abc


In [7]:
import numpy as np

In [8]:
a= [2,8,4,6,7]

In [9]:
type(a)

list

In [10]:
a= np.array(a)

In [11]:
type(a)

numpy.ndarray

In [12]:
a.dtype

dtype('int64')

In [13]:
a.ndim

1

In [14]:
a.size

5

In [15]:
len(a)

5

In [16]:
a.sum()

27

different ways to create an array

In [17]:
a1=np.array([3,5,5,6,2,894,1.24],dtype="int")

In [18]:
a1

array([  3,   5,   5,   6,   2, 894,   1])

In [19]:
type(a1)

numpy.ndarray

In [20]:
a1.dtype

dtype('int64')

In [21]:
a2= np.arange(1,9,2,dtype="float")

In [22]:
a2

array([1., 3., 5., 7.])

In [23]:
a3 = np.linspace(4,9,12)

In [24]:
a3

array([4.        , 4.45454545, 4.90909091, 5.36363636, 5.81818182,
       6.27272727, 6.72727273, 7.18181818, 7.63636364, 8.09090909,
       8.54545455, 9.        ])

In [25]:
np.logspace(1,5)

array([1.00000000e+01, 1.20679264e+01, 1.45634848e+01, 1.75751062e+01,
       2.12095089e+01, 2.55954792e+01, 3.08884360e+01, 3.72759372e+01,
       4.49843267e+01, 5.42867544e+01, 6.55128557e+01, 7.90604321e+01,
       9.54095476e+01, 1.15139540e+02, 1.38949549e+02, 1.67683294e+02,
       2.02358965e+02, 2.44205309e+02, 2.94705170e+02, 3.55648031e+02,
       4.29193426e+02, 5.17947468e+02, 6.25055193e+02, 7.54312006e+02,
       9.10298178e+02, 1.09854114e+03, 1.32571137e+03, 1.59985872e+03,
       1.93069773e+03, 2.32995181e+03, 2.81176870e+03, 3.39322177e+03,
       4.09491506e+03, 4.94171336e+03, 5.96362332e+03, 7.19685673e+03,
       8.68511374e+03, 1.04811313e+04, 1.26485522e+04, 1.52641797e+04,
       1.84206997e+04, 2.22299648e+04, 2.68269580e+04, 3.23745754e+04,
       3.90693994e+04, 4.71486636e+04, 5.68986603e+04, 6.86648845e+04,
       8.28642773e+04, 1.00000000e+05])

In [26]:
np.logspace(1,5,5)

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05])

In [27]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [28]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

2D array

In [29]:
a= np.array([21,132,51,7,54,2,72,746])

In [30]:
a

array([ 21, 132,  51,   7,  54,   2,  72, 746])

In [31]:
a.ndim

1

In [32]:
a= np.array([[21,132,2,72,746],[21,132,51,7,54]])

In [33]:
a

array([[ 21, 132,   2,  72, 746],
       [ 21, 132,  51,   7,  54]])

In [34]:
a.ndim

2

In [35]:
a[0],a[-1]

(array([ 21, 132,   2,  72, 746]), array([ 21, 132,  51,   7,  54]))

In [36]:
a[0,3]

72

In [37]:
a[1,-1]

54

In [38]:
a.shape

(2, 5)

In [39]:
a.ravel()


array([ 21, 132,   2,  72, 746,  21, 132,  51,   7,  54])

In [40]:
b = np.arange(5,800,50)

In [41]:
b

array([  5,  55, 105, 155, 205, 255, 305, 355, 405, 455, 505, 555, 605,
       655, 705, 755])

In [42]:
b.reshape(4,4)

array([[  5,  55, 105, 155],
       [205, 255, 305, 355],
       [405, 455, 505, 555],
       [605, 655, 705, 755]])

In [43]:
np.linspace(1,20,20).reshape(10,2)

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.],
       [11., 12.],
       [13., 14.],
       [15., 16.],
       [17., 18.],
       [19., 20.]])

3D array

In [44]:
 a= np.array([[[2,4,7,9],[2,3,4,5]],[[2,4,7,9],[2,3,4,5]]])

In [45]:
a

array([[[2, 4, 7, 9],
        [2, 3, 4, 5]],

       [[2, 4, 7, 9],
        [2, 3, 4, 5]]])

In [51]:
a[1][0,1:3]

array([4, 7])

In [52]:
a[1,0,1:3]

array([4, 7])

In [56]:
a[:,1:2,::3]

array([[[2, 5]],

       [[2, 5]]])

In [58]:
a = np.arange(30).reshape([3,2,5])

In [59]:
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [63]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [67]:
a.shape

(3, 2, 5)

In [71]:
a.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])